plugins:
  - jekyll-redirect-from
  - "jekyll-github-metadata"
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - README
  - tmp
