#
# default build settings (over-riding UI)
#
[build]
  # default build command
  command = "jekyll build"

[build.environment]
  # default environment
  JEKYLL_ENV = "development"

[build.processing]
  # No post processing
  skip_processing = true

#
# Production Settings
#
[context.production]
  # Enable enhanced "related post" indexing
  command = "jekyll build --lsi"

[context.production.environment]
  # set environment to enable comments & analytics
  JEKYLL_ENV = "production"

[context.production.processing]
  # Post process generated site
  skip_processing = false
  bundle = true
  minify = true
  pretty_urls = true
  compress = true

#
# Deploy Preview Context
#
[context.deploy-preview.environment]
  JEKYLL_ENV = "production"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Recurse through all the links and asset references on your page, starting
  # at the entrypoints
  recursive = true

  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true

  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = [ 
    "facebook.com", 
    ".map",
    "www.readynas.com/forum",
    "www.readynas.com/?",
    "kb.netgear.com",
    "documentation.apple.com/en/aperture",
    "frontview",
    "www.dlna.org/digital_living/faq",
    "www.dlna.org/industry",
    "qnap.com",
    "subsonic.org",
    "synology.com"
  ]

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = [
  ]

  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = true
